package app.bean;
// Generated Feb 26, 2011 1:22:36 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Feedback generated by hbm2java
 */
public class Feedback  implements java.io.Serializable {


     private int feedbackId;
     private String fullName;
     private String email;
     private String title;
     private String body;
     private Date createDate;
     private Integer readFeedback;
     private Integer visiable;

    public Feedback() {
    }

	
    public Feedback(int feedbackId, String fullName, String email, String title, String body, Date createDate) {
        this.feedbackId = feedbackId;
        this.fullName = fullName;
        this.email = email;
        this.title = title;
        this.body = body;
        this.createDate = createDate;
    }
    public Feedback(int feedbackId, String fullName, String email, String title, String body, Date createDate, Integer readFeedback, Integer visiable) {
       this.feedbackId = feedbackId;
       this.fullName = fullName;
       this.email = email;
       this.title = title;
       this.body = body;
       this.createDate = createDate;
       this.readFeedback = readFeedback;
       this.visiable = visiable;
    }
   
    public int getFeedbackId() {
        return this.feedbackId;
    }
    
    public void setFeedbackId(int feedbackId) {
        this.feedbackId = feedbackId;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Integer getReadFeedback() {
        return this.readFeedback;
    }
    
    public void setReadFeedback(Integer readFeedback) {
        this.readFeedback = readFeedback;
    }
    public Integer getVisiable() {
        return this.visiable;
    }
    
    public void setVisiable(Integer visiable) {
        this.visiable = visiable;
    }




}


