package app.bean;
// Generated Feb 26, 2011 1:22:36 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private int orderId;
     private Users users;
     private Date orderDate;
     private Date startDate;
     private Date endDate;
     private Date canceDate;
     private Integer statusOrder;
     private String fullName;
     private String address;
     private String email;
     private String phone;
     private Integer visiable;
     private Set<OrderDetails> orderDetailses = new HashSet<OrderDetails>(0);
     private Set<Payment> payments = new HashSet<Payment>(0);

    public Orders() {
    }

	
    public Orders(int orderId, Users users, Date orderDate, Date startDate, Date endDate, String fullName, String address, String email, String phone) {
        this.orderId = orderId;
        this.users = users;
        this.orderDate = orderDate;
        this.startDate = startDate;
        this.endDate = endDate;
        this.fullName = fullName;
        this.address = address;
        this.email = email;
        this.phone = phone;
    }
    public Orders(int orderId, Users users, Date orderDate, Date startDate, Date endDate, Date canceDate, Integer statusOrder, String fullName, String address, String email, String phone, Integer visiable, Set<OrderDetails> orderDetailses, Set<Payment> payments) {
       this.orderId = orderId;
       this.users = users;
       this.orderDate = orderDate;
       this.startDate = startDate;
       this.endDate = endDate;
       this.canceDate = canceDate;
       this.statusOrder = statusOrder;
       this.fullName = fullName;
       this.address = address;
       this.email = email;
       this.phone = phone;
       this.visiable = visiable;
       this.orderDetailses = orderDetailses;
       this.payments = payments;
    }
   
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public Date getCanceDate() {
        return this.canceDate;
    }
    
    public void setCanceDate(Date canceDate) {
        this.canceDate = canceDate;
    }
    public Integer getStatusOrder() {
        return this.statusOrder;
    }
    
    public void setStatusOrder(Integer statusOrder) {
        this.statusOrder = statusOrder;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public Integer getVisiable() {
        return this.visiable;
    }
    
    public void setVisiable(Integer visiable) {
        this.visiable = visiable;
    }
    public Set<OrderDetails> getOrderDetailses() {
        return this.orderDetailses;
    }
    
    public void setOrderDetailses(Set<OrderDetails> orderDetailses) {
        this.orderDetailses = orderDetailses;
    }
    public Set<Payment> getPayments() {
        return this.payments;
    }
    
    public void setPayments(Set<Payment> payments) {
        this.payments = payments;
    }




}


