package app.bean;
// Generated Feb 26, 2011 1:22:36 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Project generated by hbm2java
 */
public class Project  implements java.io.Serializable {


     private int projectId;
     private String projectName;
     private String images;
     private String description;
     private String details;
     private Date startDate;
     private Date endDate;
     private int statusProject;
     private Integer visiable;

    public Project() {
    }

	
    public Project(int projectId, String projectName, String images, String description, String details, Date startDate, Date endDate, int statusProject) {
        this.projectId = projectId;
        this.projectName = projectName;
        this.images = images;
        this.description = description;
        this.details = details;
        this.startDate = startDate;
        this.endDate = endDate;
        this.statusProject = statusProject;
    }
    public Project(int projectId, String projectName, String images, String description, String details, Date startDate, Date endDate, int statusProject, Integer visiable) {
       this.projectId = projectId;
       this.projectName = projectName;
       this.images = images;
       this.description = description;
       this.details = details;
       this.startDate = startDate;
       this.endDate = endDate;
       this.statusProject = statusProject;
       this.visiable = visiable;
    }
   
    public int getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(int projectId) {
        this.projectId = projectId;
    }
    public String getProjectName() {
        return this.projectName;
    }
    
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }
    public String getImages() {
        return this.images;
    }
    
    public void setImages(String images) {
        this.images = images;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public int getStatusProject() {
        return this.statusProject;
    }
    
    public void setStatusProject(int statusProject) {
        this.statusProject = statusProject;
    }
    public Integer getVisiable() {
        return this.visiable;
    }
    
    public void setVisiable(Integer visiable) {
        this.visiable = visiable;
    }




}


