package app.bean;
// Generated Feb 26, 2011 1:22:36 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Services generated by hbm2java
 */
public class Services  implements java.io.Serializable {


     private int servicesId;
     private Category category;
     private String servicesName;
     private String imagesSmall;
     private String desription;
     private String servicesDetails;
     private BigDecimal priceServices;
     private String unit;
     private Integer visiable;
     private Set<OrderDetails> orderDetailses = new HashSet<OrderDetails>(0);

    public Services() {
    }

	
    public Services(int servicesId, Category category, String servicesName, String desription, String servicesDetails, BigDecimal priceServices) {
        this.servicesId = servicesId;
        this.category = category;
        this.servicesName = servicesName;
        this.desription = desription;
        this.servicesDetails = servicesDetails;
        this.priceServices = priceServices;
    }
    public Services(int servicesId, Category category, String servicesName, String imagesSmall, String desription, String servicesDetails, BigDecimal priceServices, String unit, Integer visiable, Set<OrderDetails> orderDetailses) {
       this.servicesId = servicesId;
       this.category = category;
       this.servicesName = servicesName;
       this.imagesSmall = imagesSmall;
       this.desription = desription;
       this.servicesDetails = servicesDetails;
       this.priceServices = priceServices;
       this.unit = unit;
       this.visiable = visiable;
       this.orderDetailses = orderDetailses;
    }
   
    public int getServicesId() {
        return this.servicesId;
    }
    
    public void setServicesId(int servicesId) {
        this.servicesId = servicesId;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getServicesName() {
        return this.servicesName;
    }
    
    public void setServicesName(String servicesName) {
        this.servicesName = servicesName;
    }
    public String getImagesSmall() {
        return this.imagesSmall;
    }
    
    public void setImagesSmall(String imagesSmall) {
        this.imagesSmall = imagesSmall;
    }
    public String getDesription() {
        return this.desription;
    }
    
    public void setDesription(String desription) {
        this.desription = desription;
    }
    public String getServicesDetails() {
        return this.servicesDetails;
    }
    
    public void setServicesDetails(String servicesDetails) {
        this.servicesDetails = servicesDetails;
    }
    public BigDecimal getPriceServices() {
        return this.priceServices;
    }
    
    public void setPriceServices(BigDecimal priceServices) {
        this.priceServices = priceServices;
    }
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    public Integer getVisiable() {
        return this.visiable;
    }
    
    public void setVisiable(Integer visiable) {
        this.visiable = visiable;
    }
    public Set<OrderDetails> getOrderDetailses() {
        return this.orderDetailses;
    }
    
    public void setOrderDetailses(Set<OrderDetails> orderDetailses) {
        this.orderDetailses = orderDetailses;
    }




}


