package app.bean;
// Generated Feb 26, 2011 1:22:36 PM by Hibernate Tools 3.2.1.GA



/**
 * ContactUs generated by hbm2java
 */
public class ContactUs  implements java.io.Serializable {


     private int contactId;
     private String contents;
     private Integer visiable;

    public ContactUs() {
    }

	
    public ContactUs(int contactId, String contents) {
        this.contactId = contactId;
        this.contents = contents;
    }
    public ContactUs(int contactId, String contents, Integer visiable) {
       this.contactId = contactId;
       this.contents = contents;
       this.visiable = visiable;
    }
   
    public int getContactId() {
        return this.contactId;
    }
    
    public void setContactId(int contactId) {
        this.contactId = contactId;
    }
    public String getContents() {
        return this.contents;
    }
    
    public void setContents(String contents) {
        this.contents = contents;
    }
    public Integer getVisiable() {
        return this.visiable;
    }
    
    public void setVisiable(Integer visiable) {
        this.visiable = visiable;
    }




}


