package app.bean;
// Generated Mar 3, 2011 10:12:05 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * OrderDetails generated by hbm2java
 */
public class OrderDetails  implements java.io.Serializable {


     private int orderDetailsId;
     private Services services;
     private Orders orders;
     private BigDecimal unitPrice;
     private int quantity;

    public OrderDetails() {
    }

    public OrderDetails(int orderDetailsId, Services services, Orders orders, BigDecimal unitPrice, int quantity) {
       this.orderDetailsId = orderDetailsId;
       this.services = services;
       this.orders = orders;
       this.unitPrice = unitPrice;
       this.quantity = quantity;
    }

    public int getOrderDetailsId() {
        return this.orderDetailsId;
    }

    public void setOrderDetailsId(int orderDetailsId) {
        this.orderDetailsId = orderDetailsId;
    }
    public Services getServices() {
        return this.services;
    }

    public void setServices(Services services) {
        this.services = services;
    }
    public Orders getOrders() {
        return this.orders;
    }

    public void setOrders(Orders orders) {
        this.orders = orders;
    }
    public BigDecimal getUnitPrice() {
        return this.unitPrice;
    }

    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }
    public int getQuantity() {
        return this.quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }




}


