package app.bean;
// Generated Feb 26, 2011 1:22:36 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * PaymentDetails generated by hbm2java
 */
public class PaymentDetails  implements java.io.Serializable {


     private int paymentDetailsId;
     private Payment payment;
     private BigDecimal paidAmount;
     private Date datePaid;

    public PaymentDetails() {
    }

    public PaymentDetails(int paymentDetailsId, Payment payment, BigDecimal paidAmount, Date datePaid) {
       this.paymentDetailsId = paymentDetailsId;
       this.payment = payment;
       this.paidAmount = paidAmount;
       this.datePaid = datePaid;
    }
   
    public int getPaymentDetailsId() {
        return this.paymentDetailsId;
    }
    
    public void setPaymentDetailsId(int paymentDetailsId) {
        this.paymentDetailsId = paymentDetailsId;
    }
    public Payment getPayment() {
        return this.payment;
    }
    
    public void setPayment(Payment payment) {
        this.payment = payment;
    }
    public BigDecimal getPaidAmount() {
        return this.paidAmount;
    }
    
    public void setPaidAmount(BigDecimal paidAmount) {
        this.paidAmount = paidAmount;
    }
    public Date getDatePaid() {
        return this.datePaid;
    }
    
    public void setDatePaid(Date datePaid) {
        this.datePaid = datePaid;
    }




}


