package app.bean;
// Generated Feb 26, 2011 1:22:36 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Payment generated by hbm2java
 */
public class Payment  implements java.io.Serializable {


     private int paymentId;
     private Orders orders;
     private Date paymentDateFinal;
     private BigDecimal totalAmount;
     private BigDecimal duePay;
     private int typePay;
     private Integer statusPay;
     private Set<PaymentDetails> paymentDetailses = new HashSet<PaymentDetails>(0);

    public Payment() {
    }

	
    public Payment(int paymentId, Orders orders, Date paymentDateFinal, BigDecimal totalAmount, int typePay) {
        this.paymentId = paymentId;
        this.orders = orders;
        this.paymentDateFinal = paymentDateFinal;
        this.totalAmount = totalAmount;
        this.typePay = typePay;
    }
    public Payment(int paymentId, Orders orders, Date paymentDateFinal, BigDecimal totalAmount, BigDecimal duePay, int typePay, Integer statusPay, Set<PaymentDetails> paymentDetailses) {
       this.paymentId = paymentId;
       this.orders = orders;
       this.paymentDateFinal = paymentDateFinal;
       this.totalAmount = totalAmount;
       this.duePay = duePay;
       this.typePay = typePay;
       this.statusPay = statusPay;
       this.paymentDetailses = paymentDetailses;
    }
   
    public int getPaymentId() {
        return this.paymentId;
    }
    
    public void setPaymentId(int paymentId) {
        this.paymentId = paymentId;
    }
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }
    public Date getPaymentDateFinal() {
        return this.paymentDateFinal;
    }
    
    public void setPaymentDateFinal(Date paymentDateFinal) {
        this.paymentDateFinal = paymentDateFinal;
    }
    public BigDecimal getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }
    public BigDecimal getDuePay() {
        return this.duePay;
    }
    
    public void setDuePay(BigDecimal duePay) {
        this.duePay = duePay;
    }
    public int getTypePay() {
        return this.typePay;
    }
    
    public void setTypePay(int typePay) {
        this.typePay = typePay;
    }
    public Integer getStatusPay() {
        return this.statusPay;
    }
    
    public void setStatusPay(Integer statusPay) {
        this.statusPay = statusPay;
    }
    public Set<PaymentDetails> getPaymentDetailses() {
        return this.paymentDetailses;
    }
    
    public void setPaymentDetailses(Set<PaymentDetails> paymentDetailses) {
        this.paymentDetailses = paymentDetailses;
    }




}


